2024-06-17 12:48:07,333 [INFO]  starting up 24-06-17-1248_P1-test at 1.5159565833746456
2024-06-17 12:48:07,353 [INFO]  git SHA: dc6e0c15150cc2db1667ec15431faef8e3cd16d2
2024-06-17 12:48:07,353 [INFO]  Configuration file: config/m2/1.json
2024-06-17 12:48:07,354 [INFO]  parameters {'reward_info': {'-4': {'desc': 'pattern_1', 'image': 'images[0]'}, '-3': {'desc': 'pattern_2', 'image': 'images[1]'}, '-2': {'desc': 'pattern_3', 'image': 'images[2]'}, '-1': {'desc': 'pattern_4', 'image': 'images[3]'}, '0': {'desc': 'pattern_5', 'image': 'images[4]'}, '1': {'desc': 'pattern_6', 'image': 'images[5]'}, '2': {'desc': 'pattern_7', 'image': 'images[6]'}, '3': {'desc': 'pattern_8', 'image': 'images[7]'}, '4': {'desc': 'pattern_9', 'image': 'images[8]'}}, 'images': ['pattern_1.png', 'pattern_2.png', 'pattern_3.png', 'pattern_4.png', 'pattern_5.png', 'pattern_6.png', 'pattern_7.png', 'pattern_8.png', 'pattern_9.png'], 'points_per_cent': 1, 'revealed': True, 'layout': [[0.0, 0.5], [-0.27032040872779883, 0.4206267664155905], [-0.4548159976772592, 0.20770750650094316], [-0.4949107209404664, -0.07115741913664247], [-0.3778747871771292, -0.3274303669726425], [-0.14086627842071486, -0.4797464868072487], [0.14086627842071464, -0.47974648680724874], [0.37787478717712886, -0.32743036697264283], [0.4949107209404664, -0.07115741913664264], [0.4548159976772592, 0.20770750650094305], [0.27032040872779883, 0.4206267664155906]]}
2024-06-17 12:48:08,550 [INFO]  begin calibrate_gaze_tolerance
2024-06-17 12:48:08,551 [DEBUG]  message: We're going to check how well the eyetracker is working. (None)
2024-06-17 12:48:08,707 [DEBUG]  message: When the board comes up, just look at the O's as they appear. They should disappear. If it's not working, press X. (None)
2024-06-17 12:48:09,095 [ERROR]  Expected a list with a dictionary for trial data, got: [[], [], [], [], [], [], [], [], [], [], []]
2024-06-17 12:48:09,095 [INFO]  begin trial {"kind": "CalibrationTrial", "graph": [[], [], [], [], [], [], [], [], [], [], []], "rewards": [1, null, null, 2, 3, 3, null, null, 0, -4, null], "reward_info": {"-4": {"desc": "pattern_1", "image": "images[0]"}, "-3": {"desc": "pattern_2", "image": "images[1]"}, "-2": {"desc": "pattern_3", "image": "images[2]"}, "-1": {"desc": "pattern_4", "image": "images[3]"}, "0": {"desc": "pattern_5", "image": "images[4]"}, "1": {"desc": "pattern_6", "image": "images[5]"}, "2": {"desc": "pattern_7", "image": "images[6]"}, "3": {"desc": "pattern_8", "image": "images[7]"}, "4": {"desc": "pattern_9", "image": "images[8]"}}, "initial_stage": "planning", "hide_states": false, "hide_rewards_while_acting": false, "hide_edges_while_acting": false, "gaze_contingent": true, "gaze_tolerance": 1.5, "fixation_lag": 0.1, "start": 6}
2024-06-17 12:48:09,095 [ERROR]  Caught exception in stage calibrate_gaze_tolerance
Traceback (most recent call last):
  File "/Users/labadmin/twostep-eyetracking/experiment.py", line 36, in wrapper
    f(self, *args, **kwargs)
  File "/Users/labadmin/twostep-eyetracking/experiment.py", line 530, in calibrate_gaze_tolerance
    result = gt.run()
  File "/Users/labadmin/twostep-eyetracking/trial.py", line 582, in run
    assert self.eyelink
AssertionError
2024-06-17 12:48:44,396 [INFO]  starting up 24-06-17-1248_P1-test at 2.002760583360214
2024-06-17 12:48:44,417 [INFO]  git SHA: dc6e0c15150cc2db1667ec15431faef8e3cd16d2
2024-06-17 12:48:44,417 [INFO]  Configuration file: config/m2/1.json
2024-06-17 12:48:44,418 [INFO]  parameters {'reward_info': {'-4': {'desc': 'pattern_1', 'image': 'images[0]'}, '-3': {'desc': 'pattern_2', 'image': 'images[1]'}, '-2': {'desc': 'pattern_3', 'image': 'images[2]'}, '-1': {'desc': 'pattern_4', 'image': 'images[3]'}, '0': {'desc': 'pattern_5', 'image': 'images[4]'}, '1': {'desc': 'pattern_6', 'image': 'images[5]'}, '2': {'desc': 'pattern_7', 'image': 'images[6]'}, '3': {'desc': 'pattern_8', 'image': 'images[7]'}, '4': {'desc': 'pattern_9', 'image': 'images[8]'}}, 'images': ['pattern_1.png', 'pattern_2.png', 'pattern_3.png', 'pattern_4.png', 'pattern_5.png', 'pattern_6.png', 'pattern_7.png', 'pattern_8.png', 'pattern_9.png'], 'points_per_cent': 1, 'revealed': True, 'layout': [[0.0, 0.5], [-0.27032040872779883, 0.4206267664155905], [-0.4548159976772592, 0.20770750650094316], [-0.4949107209404664, -0.07115741913664247], [-0.3778747871771292, -0.3274303669726425], [-0.14086627842071486, -0.4797464868072487], [0.14086627842071464, -0.47974648680724874], [0.37787478717712886, -0.32743036697264283], [0.4949107209404664, -0.07115741913664264], [0.4548159976772592, 0.20770750650094305], [0.27032040872779883, 0.4206267664155906]]}
2024-06-17 12:48:45,598 [INFO]  begin calibrate_gaze_tolerance
2024-06-17 12:48:45,598 [DEBUG]  message: We're going to check how well the eyetracker is working. (None)
2024-06-17 12:48:46,090 [DEBUG]  message: When the board comes up, just look at the O's as they appear. They should disappear. If it's not working, press X. (None)
2024-06-17 12:48:46,596 [ERROR]  Expected a list with a dictionary for trial data, got: [[], [], [], [], [], [], [], [], [], [], []]
2024-06-17 12:48:46,596 [INFO]  begin trial {"kind": "CalibrationTrial", "graph": [[], [], [], [], [], [], [], [], [], [], []], "rewards": [1, null, null, 2, 3, 3, null, null, 0, -4, null], "reward_info": {"-4": {"desc": "pattern_1", "image": "images[0]"}, "-3": {"desc": "pattern_2", "image": "images[1]"}, "-2": {"desc": "pattern_3", "image": "images[2]"}, "-1": {"desc": "pattern_4", "image": "images[3]"}, "0": {"desc": "pattern_5", "image": "images[4]"}, "1": {"desc": "pattern_6", "image": "images[5]"}, "2": {"desc": "pattern_7", "image": "images[6]"}, "3": {"desc": "pattern_8", "image": "images[7]"}, "4": {"desc": "pattern_9", "image": "images[8]"}}, "initial_stage": "planning", "hide_states": false, "hide_rewards_while_acting": false, "hide_edges_while_acting": false, "gaze_contingent": true, "gaze_tolerance": 1.5, "fixation_lag": 0.1, "start": 6}
2024-06-17 12:48:46,597 [ERROR]  Caught exception in stage calibrate_gaze_tolerance
Traceback (most recent call last):
  File "/Users/labadmin/twostep-eyetracking/experiment.py", line 36, in wrapper
    f(self, *args, **kwargs)
  File "/Users/labadmin/twostep-eyetracking/experiment.py", line 530, in calibrate_gaze_tolerance
    result = gt.run()
  File "/Users/labadmin/twostep-eyetracking/trial.py", line 582, in run
    assert self.eyelink
AssertionError
